# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lambdainst', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnuser',
            name='campaign',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
